spring:
  port: 8080
  forward-headers-strategy: framework
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true
    groups-order: ASC

logging:
  level:
    com.ganzi.backend: info

animal:
  api:
    base-url: https://apis.data.go.kr/1543061/abandonmentPublicService_v2
    service-key: ${ANIMAL_API_SERVICE_KEY}
    timeout:
      connect: 10000
      read: 60000

upstage:
  api:
    base-url: ${UPSTAGE_API_BASE_URL:https://api.upstage.ai/v1}
    key: ${UPSTAGE_API_KEY}
  embedding:
    endpoint: /solar/embeddings
    model: solar-embedding-1-large-passage

  ai-space:
    api-key: ${UPSTAGE_AI_API_KEY}
    endpoint-url: ${UPSTAGE_AI_SPACE_ENDPOINT_URL:https://api.upstage.ai/v1/chat/completions}
